import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "Checking if this is absolute",
    default: "Next.js Tutorials | codevolution",
    template: "%s | Codevolution",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-800 text-white py-10 text-center"> Header </header>
        {children}
        <footer className="bg-pink-800 text-white py-10 text-center"> Footer </footer>
        </body>
    </html>
  )
}
